#!/usr/bin/env python3
"""Generate the compile workload.

The throughput half of the experiment is a `make -j8` of a synthetic C project.
It is generated rather than downloaded so that the benchmark is hermetic: no
network, no distro package versions, no upstream drift between the day the
numbers were taken and the day someone tries to reproduce them.

Properties that were deliberately chosen:

  * Deterministic. Fixed PRNG seed, so the same tree is produced everywhere and
    two runs compile literally identical bytes.
  * Compute-bound, not I/O-bound. Files are small enough to stay in page cache
    after the first build; what is being measured is compiler CPU time, because
    that is the load per-core EPP is supposed to help with.
  * Enough translation units to keep 8 threads fed. With fewer TUs than threads
    the tail of the build serialises and the energy comparison is dominated by
    the ramp-down rather than the steady state.
  * Similar per-file cost. Wildly uneven TUs make `make -j` finish with one long
    pole, which adds variance without adding information.
"""
import argparse
import os
import random
import shutil
import sys

HEADER = """/* generated by scripts/workload.py - do not edit */
#include <stdint.h>
#include <math.h>
"""


def gen_function(rng, idx):
    """A function that is slow to compile: deep expressions, many locals."""
    lines = [f"double f{idx}(double x, double y)", "{"]
    lines.append("\tdouble a0 = x + y;")
    nvars = rng.randint(24, 40)
    for v in range(1, nvars):
        p = rng.randint(0, v - 1)
        q = rng.randint(0, v - 1)
        op = rng.choice(["+", "-", "*"])
        fn = rng.choice(["sin", "cos", "sqrt", "fabs", "exp", "log1p"])
        lines.append(f"\tdouble a{v} = {fn}(a{p} {op} a{q} + {rng.random():.9f});")
    # A switch keeps the optimiser honest and adds real front-end work.
    lines.append(f"\tswitch ((int)a{nvars - 1} & 7) {{")
    for c in range(8):
        lines.append(f"\tcase {c}: return a{rng.randint(0, nvars - 1)} * {c + 1}.5;")
    lines.append("\t}")
    lines.append(f"\treturn a{nvars - 1};")
    lines.append("}")
    return "\n".join(lines)


def generate(path, nfiles, nfuncs, seed):
    rng = random.Random(seed)
    if os.path.exists(path):
        shutil.rmtree(path)
    os.makedirs(path)

    for i in range(nfiles):
        body = [HEADER]
        for j in range(nfuncs):
            body.append(gen_function(rng, i * nfuncs + j))
        with open(os.path.join(path, f"mod{i:03d}.c"), "w") as f:
            f.write("\n\n".join(body) + "\n")

    with open(os.path.join(path, "Makefile"), "w") as f:
        f.write(
            "# generated by scripts/workload.py - do not edit\n"
            "CC ?= cc\n"
            # -O2 and -fno-lto: real optimiser work, but no link-time phase, so
            # the build stays parallel to the very end.
            "CFLAGS ?= -O2 -fno-lto -w\n"
            f"OBJS := {' '.join(f'mod{i:03d}.o' for i in range(nfiles))}\n"
            "all: $(OBJS)\n"
            "%.o: %.c\n"
            "\t$(CC) $(CFLAGS) -c $< -o $@\n"
            "clean:\n"
            "\trm -f $(OBJS)\n"
            ".PHONY: all clean\n"
        )
    return path


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--path", default="build/genproj")
    ap.add_argument("--files", type=int, default=512,
                    help="translation units (>= 4x nr_cpus keeps -j8 fed)")
    ap.add_argument("--funcs", type=int, default=8, help="functions per file")
    ap.add_argument("--seed", type=int, default=20260721)
    ap.add_argument("--force", action="store_true",
                    help="regenerate even if the tree already exists")
    args = ap.parse_args()

    stamp = os.path.join(args.path, ".stamp")
    want = f"{args.files}:{args.funcs}:{args.seed}\n"
    if not args.force and os.path.exists(stamp):
        with open(stamp) as f:
            if f.read() == want:
                print(f"{args.path}: up to date ({args.files} files)")
                return 0

    generate(args.path, args.files, args.funcs, args.seed)
    with open(stamp, "w") as f:
        f.write(want)
    print(f"{args.path}: generated {args.files} files x {args.funcs} functions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
